import path from 'path';
import fs from 'fs-extra';

import type { StudioBlockerHandoff } from '../contracts/studio-blocker-handoff-contract.js';

export type BootstrapComplianceRemediationResult = {
  handled: boolean;
  ok: boolean;
  summary: string;
  verifyCommand: string;
  appliedFixes: Array<{ path: string; action: string; outcome: string }>;
  rollbackCommand?: string;
};

const ENTERPRISE_BOOTSTRAP_BLOCKER_PATTERNS = [
  'profile.enterprise.ci',
  'profile.enterprise.compatibility-matrix',
  'profile.enterprise.mirror-config',
];

export function isBootstrapComplianceHandoff(
  handoff: Pick<StudioBlockerHandoff, 'cardId' | 'cardLabel' | 'blockers'>
): boolean {
  if (handoff.cardId === 'bootstrap') {
    return true;
  }
  if (/bootstrap compliance/i.test(handoff.cardLabel ?? '')) {
    return true;
  }
  return handoff.blockers.some((blocker) =>
    ENTERPRISE_BOOTSTRAP_BLOCKER_PATTERNS.some((pattern) => blocker.includes(pattern))
  );
}

export function normalizeBootstrapComplianceCommand(command: string | undefined): string {
  const trimmed = command?.trim() || 'npx rapidkit bootstrap';
  const isBootstrapCommand = /(?:^|\s)(?:rapidkit\s+)?bootstrap(?:\s|$)/.test(trimmed);
  if (!isBootstrapCommand) {
    return trimmed;
  }

  let normalized = trimmed;
  if (!/(?:^|\s)--ci(?:\s|$)/.test(normalized)) {
    if (/(?:^|\s)--json(?:\s|$)/.test(normalized)) {
      normalized = normalized.replace(/(?:^|\s)--json(?:\s|$)/, (match) => {
        const prefix = match.startsWith(' ') ? ' ' : '';
        const suffix = match.endsWith(' ') ? ' ' : '';
        return `${prefix}--ci --json${suffix}`;
      });
    } else {
      normalized = `${normalized} --ci`;
    }
  }
  if (!/(?:^|\s)--json(?:\s|$)/.test(normalized)) {
    normalized = `${normalized} --json`;
  }
  return normalized.trim();
}

function buildCompatibilityMatrix(generatedAt: string): Record<string, unknown> {
  return {
    schemaVersion: 'rapidkit.compatibility-matrix.v1',
    generatedAt,
    source: 'workspai-studio',
    runtimes: {},
    notes: [
      'Minimal enterprise baseline generated by Workspai Studio. Add runtime/version entries as the workspace governance policy matures.',
    ],
  };
}

function buildMirrorConfig(generatedAt: string): Record<string, unknown> {
  return {
    schema_version: '1.0',
    enabled: false,
    strategy: 'on-demand',
    artifacts: [],
    created_at: generatedAt,
    note: 'Generated by Workspai Studio to satisfy the enterprise bootstrap baseline. Set enabled: true and add artifact entries to activate mirroring.',
  };
}

async function writeJsonIfMissing(
  filePath: string,
  payload: Record<string, unknown>
): Promise<'applied' | 'unchanged'> {
  if (await fs.pathExists(filePath)) {
    return 'unchanged';
  }
  await fs.ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  return 'applied';
}

export async function applyBootstrapComplianceRemediation(input: {
  workspacePath: string;
  handoff: Pick<StudioBlockerHandoff, 'cardId' | 'cardLabel' | 'blockers' | 'sourceCommand'>;
  generatedAt?: string;
}): Promise<BootstrapComplianceRemediationResult> {
  if (!isBootstrapComplianceHandoff(input.handoff)) {
    return {
      handled: false,
      ok: false,
      summary: 'Not a bootstrap compliance handoff.',
      verifyCommand: normalizeBootstrapComplianceCommand(input.handoff.sourceCommand),
      appliedFixes: [],
    };
  }

  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const rapidkitDir = path.join(input.workspacePath, '.rapidkit');
  const compatibilityMatrixPath = path.join(rapidkitDir, 'compatibility-matrix.json');
  const mirrorConfigPath = path.join(rapidkitDir, 'mirror-config.json');
  const appliedFixes: BootstrapComplianceRemediationResult['appliedFixes'] = [];

  try {
    const needsCompatibilityMatrix = input.handoff.blockers.some((blocker) =>
      blocker.includes('profile.enterprise.compatibility-matrix')
    );
    const needsMirrorConfig = input.handoff.blockers.some((blocker) =>
      blocker.includes('profile.enterprise.mirror-config')
    );

    if (needsCompatibilityMatrix) {
      const outcome = await writeJsonIfMissing(
        compatibilityMatrixPath,
        buildCompatibilityMatrix(generatedAt)
      );
      appliedFixes.push({
        path: path.relative(input.workspacePath, compatibilityMatrixPath),
        action: 'file-create',
        outcome,
      });
    }

    if (needsMirrorConfig) {
      const outcome = await writeJsonIfMissing(mirrorConfigPath, buildMirrorConfig(generatedAt));
      appliedFixes.push({
        path: path.relative(input.workspacePath, mirrorConfigPath),
        action: 'file-create',
        outcome,
      });
    }

    const createdCount = appliedFixes.filter((fix) => fix.outcome === 'applied').length;
    const unchangedCount = appliedFixes.filter((fix) => fix.outcome === 'unchanged').length;
    const ciOnly =
      appliedFixes.length === 0 &&
      input.handoff.blockers.some((blocker) => blocker.includes('profile.enterprise.ci'));

    const rollbackFixes = appliedFixes.filter((fix) => fix.outcome === 'applied');

    return {
      handled: true,
      ok: true,
      summary: ciOnly
        ? 'Bootstrap compliance will be verified in deterministic CI mode.'
        : `Bootstrap compliance baseline ready (${createdCount} created, ${unchangedCount} already present).`,
      verifyCommand: normalizeBootstrapComplianceCommand(input.handoff.sourceCommand),
      appliedFixes,
      rollbackCommand:
        rollbackFixes.length > 0
          ? `git checkout -- ${rollbackFixes.map((fix) => JSON.stringify(fix.path)).join(' ')}`
          : undefined,
    };
  } catch (error) {
    return {
      handled: true,
      ok: false,
      summary: error instanceof Error ? error.message : String(error),
      verifyCommand: normalizeBootstrapComplianceCommand(input.handoff.sourceCommand),
      appliedFixes,
    };
  }
}
