import {
  buildWorkspaceAgentContextCliArgs,
  buildWorkspaceAgentSyncCliArgs,
} from './agentContextPack';
import { resolveDashboardCommandSurface } from '../contracts/dashboardCommandSurface';

export type DashboardCommandScope = 'workspace' | 'project' | 'module' | 'system';

export type DashboardCommandExecutionMode =
  | 'webview-local'
  | 'extension-host-handler'
  | 'vscode-command'
  | 'terminal-rapidkit'
  | 'terminal-shell';

export type DashboardCommandPayloadKind =
  | 'none'
  | 'workspace'
  | 'project-path'
  | 'project-context'
  | 'module-maintenance';

export type DashboardCommandContract = {
  id: string;
  label: string;
  scope: DashboardCommandScope;
  executionMode: DashboardCommandExecutionMode;
  trackActivity: boolean;
  requiresWorkspace?: boolean;
  requiresProject?: boolean;
  cliArgs?: string[];
  vscodeCommand?: string;
  payloadKind?: DashboardCommandPayloadKind;
  payloadDefaults?: Record<string, unknown>;
};

export const DASHBOARD_COMMAND_CONTRACTS = {
  openSetup: {
    id: 'openSetup',
    label: 'Open Setup',
    scope: 'system',
    executionMode: 'webview-local',
    trackActivity: false,
  },
  openCreateWorkspace: {
    id: 'openCreateWorkspace',
    label: 'Create Workspace',
    scope: 'system',
    executionMode: 'webview-local',
    trackActivity: false,
  },
  refreshModules: {
    id: 'refreshModules',
    label: 'Refresh Modules',
    scope: 'system',
    executionMode: 'extension-host-handler',
    trackActivity: false,
  },
  importWorkspace: {
    id: 'importWorkspace',
    label: 'Import Workspace',
    scope: 'system',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.importWorkspace',
  },
  importProject: {
    id: 'importProject',
    label: 'Import Project',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.importProject',
  },
  adoptProject: {
    id: 'adoptProject',
    label: 'Adopt Project',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.adoptProject',
  },
  quickSwitchWorkspace: {
    id: 'quickSwitchWorkspace',
    label: 'Switch Workspace',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.quickSwitchWorkspace',
  },
  checkWorkspaceHealth: {
    id: 'checkWorkspaceHealth',
    label: 'Workspace Doctor',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['doctor', 'workspace'],
    vscodeCommand: 'workspai.checkWorkspaceHealth',
  },
  exportWorkspace: {
    id: 'exportWorkspace',
    label: 'Export Workspace',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.exportWorkspace',
  },
  workspaceBootstrap: {
    id: 'workspaceBootstrap',
    label: 'Workspace Bootstrap',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['bootstrap'],
    vscodeCommand: 'workspai.workspaceBootstrap',
  },
  workspaceSetup: {
    id: 'workspaceSetup',
    label: 'Setup',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['setup'],
    vscodeCommand: 'workspai.workspaceSetup',
  },
  workspaceSync: {
    id: 'workspaceSync',
    label: 'Workspace Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'sync'],
    vscodeCommand: 'workspai.workspaceSync',
  },
  workspaceFoundationEnsure: {
    id: 'workspaceFoundationEnsure',
    label: 'Foundation Ensure',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'foundation', 'ensure', '--json'],
    vscodeCommand: 'workspai.workspaceFoundationEnsure',
    payloadDefaults: { mode: 'ensure', json: true },
  },
  workspaceContractInspect: {
    id: 'workspaceContractInspect',
    label: 'Contract Inspect',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'inspect', '--json'],
    vscodeCommand: 'workspai.workspaceContractInspect',
  },
  workspaceContractVerify: {
    id: 'workspaceContractVerify',
    label: 'Contract Verify',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'verify', '--strict', '--json'],
    vscodeCommand: 'workspai.workspaceContractVerify',
  },
  workspaceContractInit: {
    id: 'workspaceContractInit',
    label: 'Contract Init',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'init'],
    vscodeCommand: 'workspai.workspaceContractInit',
  },
  workspaceContractGraph: {
    id: 'workspaceContractGraph',
    label: 'Workspace Graph',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'graph', '--json'],
    vscodeCommand: 'workspai.workspaceContractGraph',
  },
  workspaceRunTest: {
    id: 'workspaceRunTest',
    label: 'Workspace Test',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'test'],
    vscodeCommand: 'workspai.workspaceRunTest',
  },
  workspaceRunInit: {
    id: 'workspaceRunInit',
    label: 'Workspace Init',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'init'],
    vscodeCommand: 'workspai.workspaceRunInit',
  },
  workspaceRunBuild: {
    id: 'workspaceRunBuild',
    label: 'Workspace Build',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'build'],
    vscodeCommand: 'workspai.workspaceRunBuild',
  },
  workspaceRunStart: {
    id: 'workspaceRunStart',
    label: 'Workspace Start',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'start'],
    vscodeCommand: 'workspai.workspaceRunStart',
  },
  workspaceTerminal: {
    id: 'workspaceTerminal',
    label: 'Workspace Terminal',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceTerminal',
  },
  workspaceAnalyze: {
    id: 'workspaceAnalyze',
    label: 'Workspace Analyze',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['analyze', '--json'],
    vscodeCommand: 'workspai.workspaceAnalyze',
  },
  workspaceReadiness: {
    id: 'workspaceReadiness',
    label: 'Release Readiness',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['readiness'],
    vscodeCommand: 'workspai.workspaceReadiness',
  },
  workspacePipeline: {
    id: 'workspacePipeline',
    label: 'Governance Gate',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['pipeline', '--json', '--strict'],
    vscodeCommand: 'workspai.workspacePipeline',
  },
  workspaceModel: {
    id: 'workspaceModel',
    label: 'Workspace Model',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'model', '--json', '--write'],
    vscodeCommand: 'workspai.workspaceModel',
  },
  workspaceIntelligenceSnapshot: {
    id: 'workspaceIntelligenceSnapshot',
    label: 'Intelligence Snapshot',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'snapshot', '--json'],
    vscodeCommand: 'workspai.workspaceIntelligenceSnapshot',
  },
  workspaceDiff: {
    id: 'workspaceDiff',
    label: 'Workspace Diff',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'diff', '--json'],
    vscodeCommand: 'workspai.workspaceDiff',
  },
  workspaceImpact: {
    id: 'workspaceImpact',
    label: 'Workspace Impact',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'impact', '--json'],
    vscodeCommand: 'workspai.workspaceImpact',
  },
  workspaceVerify: {
    id: 'workspaceVerify',
    label: 'Workspace Verify',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: [
      'workspace',
      'verify',
      '--from-impact',
      '.rapidkit/reports/workspace-impact-last-run.json',
      '--json',
    ],
    vscodeCommand: 'workspai.workspaceVerify',
  },
  workspaceImpactLens: {
    id: 'workspaceImpactLens',
    label: 'Workspace Advisor',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'workspace',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'workspace_intelligence',
    },
  },
  workspaceContextAgent: {
    id: 'workspaceContextAgent',
    label: 'Agent Context Pack',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: buildWorkspaceAgentContextCliArgs(),
    vscodeCommand: 'workspai.workspaceContextAgent',
  },
  workspaceAgentSync: {
    id: 'workspaceAgentSync',
    label: 'Agent Grounding Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: buildWorkspaceAgentSyncCliArgs(),
    vscodeCommand: 'workspai.workspaceAgentSync',
  },
  workspaceIntelligenceChain: {
    id: 'workspaceIntelligenceChain',
    label: 'Intelligence Chain',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceIntelligenceChain',
  },
  workspaceAutopilotRelease: {
    id: 'workspaceAutopilotRelease',
    label: 'Autopilot Release',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['autopilot', 'release'],
    vscodeCommand: 'workspai.workspaceAutopilotRelease',
  },
  workspaceShare: {
    id: 'workspaceShare',
    label: 'Share Bundle',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.exportWorkspaceShareBundle',
  },
  workspaceSnapshotCreate: {
    id: 'workspaceSnapshotCreate',
    label: 'Recovery Snapshot',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot', 'create'],
    vscodeCommand: 'workspai.workspaceSnapshotCreate',
  },
  workspaceSnapshot: {
    id: 'workspaceSnapshot',
    label: 'Recovery Snapshot Tools',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceSnapshot',
  },
  workspaceSnapshotList: {
    id: 'workspaceSnapshotList',
    label: 'List Snapshots',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceSnapshotList',
  },
  workspaceSnapshotInspect: {
    id: 'workspaceSnapshotInspect',
    label: 'Inspect Snapshot',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceSnapshotInspect',
  },
  workspaceSnapshotRestore: {
    id: 'workspaceSnapshotRestore',
    label: 'Restore Snapshot',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceSnapshotRestore',
  },
  workspacePolicyShow: {
    id: 'workspacePolicyShow',
    label: 'Policy Review',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'policy', 'show'],
    vscodeCommand: 'workspai.workspacePolicyShow',
  },
  mirrorSync: {
    id: 'mirrorSync',
    label: 'Mirror Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'sync'],
    vscodeCommand: 'workspai.mirrorSync',
  },
  mirrorStatus: {
    id: 'mirrorStatus',
    label: 'Mirror Status',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'status'],
    vscodeCommand: 'workspai.mirrorStatus',
  },
  cacheStatus: {
    id: 'cacheStatus',
    label: 'Cache Status',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['cache', 'status'],
    vscodeCommand: 'workspai.cacheStatus',
  },
  workspaceInfra: {
    id: 'workspaceInfra',
    label: 'Infra Plan',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'plan'],
    vscodeCommand: 'workspai.infra',
  },
  workspaceArchive: {
    id: 'workspaceArchive',
    label: 'Archive Tools',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceArchive',
  },
  workspaceArchiveVerify: {
    id: 'workspaceArchiveVerify',
    label: 'Verify Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceArchiveVerify',
  },
  workspaceArchiveInspect: {
    id: 'workspaceArchiveInspect',
    label: 'Inspect Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceArchiveInspect',
  },
  workspaceArchiveDoctor: {
    id: 'workspaceArchiveDoctor',
    label: 'Doctor Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceArchiveDoctor',
  },
  projectTerminal: {
    id: 'projectTerminal',
    label: 'Project Terminal',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectTerminal',
  },
  projectInit: {
    id: 'projectInit',
    label: 'Project Init',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['init'],
    vscodeCommand: 'workspai.projectInit',
  },
  projectDev: {
    id: 'projectDev',
    label: 'Project Dev',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['dev'],
    vscodeCommand: 'workspai.projectDev',
  },
  projectStop: {
    id: 'projectStop',
    label: 'Project Stop',
    scope: 'project',
    executionMode: 'terminal-shell',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectStop',
  },
  projectTest: {
    id: 'projectTest',
    label: 'Project Test',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['test'],
    vscodeCommand: 'workspai.projectTest',
  },
  projectDoctor: {
    id: 'projectDoctor',
    label: 'Project Doctor',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['doctor', 'project'],
    vscodeCommand: 'workspai.projectDoctor',
    payloadKind: 'project-path',
    payloadDefaults: {
      preferredAction: 'check',
    },
  },
  projectArchitecture: {
    id: 'projectArchitecture',
    label: 'Architecture Map',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openArchitectureMap',
    payloadKind: 'project-context',
  },
  projectIncident: {
    id: 'projectIncident',
    label: 'Studio',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openIncidentStudio',
    payloadKind: 'project-context',
  },
  projectAI: {
    id: 'projectAI',
    label: 'Workspace Advisor',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectRelease: {
    id: 'projectRelease',
    label: 'Release Commander',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.aiReleaseReadinessCommander',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectImpact: {
    id: 'projectImpact',
    label: 'Workspace Advisor',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectBrowser: {
    id: 'projectBrowser',
    label: 'Project Browser',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectBrowser',
  },
  projectBuild: {
    id: 'projectBuild',
    label: 'Project Build',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['build'],
    vscodeCommand: 'workspai.projectBuild',
  },
  projectLint: {
    id: 'projectLint',
    label: 'Project Lint',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['lint'],
    vscodeCommand: 'workspai.projectLint',
  },
  projectFormat: {
    id: 'projectFormat',
    label: 'Project Format',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['format'],
    vscodeCommand: 'workspai.projectFormat',
  },
  moduleDiff: {
    id: 'moduleDiff',
    label: 'Module Diff',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['diff', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleDiff',
  },
  moduleRollback: {
    id: 'moduleRollback',
    label: 'Module Rollback',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['rollback', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleRollback',
  },
  moduleUninstall: {
    id: 'moduleUninstall',
    label: 'Module Uninstall',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['uninstall', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleUninstall',
  },
  moduleUpgrade: {
    id: 'moduleUpgrade',
    label: 'Module Upgrade',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['upgrade', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleUpgrade',
  },
  moduleCheckpoint: {
    id: 'moduleCheckpoint',
    label: 'Module Checkpoint',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['checkpoint', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleCheckpoint',
  },
} as const satisfies Record<string, DashboardCommandContract>;

export type DashboardCommandId = keyof typeof DASHBOARD_COMMAND_CONTRACTS;

export function resolveDashboardCommandContract(
  command: string
): DashboardCommandContract | undefined {
  return DASHBOARD_COMMAND_CONTRACTS[command as DashboardCommandId];
}

export function getDashboardCommandActivity(command: string): {
  label: string;
  scope: DashboardCommandScope;
} {
  const surface = resolveDashboardCommandSurface(command);
  if (surface) {
    return { label: surface.label, scope: surface.scope };
  }

  const contract = resolveDashboardCommandContract(command);
  if (contract) {
    return { label: contract.label, scope: contract.scope };
  }
  return {
    label: command.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
    scope: 'system',
  };
}
