export const PROJECT_REFRESH_WATCH_PATTERNS = [
  '**/.workspai/project.json',
  '**/.workspai/context.json',
  '**/.workspai/registry.json',
  '**/.workspai/imported-projects.json',
  '**/.workspai/workspace-registry.v1.json',
  '**/.rapidkit/project.json',
  '**/.rapidkit/context.json',
  '**/.rapidkit/registry.json',
  '**/.rapidkit/imported-projects.json',
  '**/registry.json',
  '**/pyproject.toml',
  '**/requirements.txt',
  '**/package.json',
  '**/go.mod',
  '**/pom.xml',
  '**/build.gradle',
  '**/build.gradle.kts',
  '**/settings.gradle',
  '**/settings.gradle.kts',
  '**/composer.json',
  '**/Cargo.toml',
  '**/mix.exs',
  '**/Gemfile',
] as const;
